version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/:/app/
    restart: always
    ports:
      - ${DOCKER_NGINX_API_PORT}:80
    depends_on:
      - php

  php:
    build: ./docker/php
    restart: always
    working_dir: /app
    volumes:
      - ./app/:/app/
      - ./.env:/etc/environment
      - composer:/root/.composer/cache
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_BASE_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${DOCKER_MYSQL_PORT}:3306

volumes:
  composer: